# Generated by Django 3.1 on 2020-08-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_examplemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='pic_folder/default.jpg', upload_to='pic_folder/'),
        ),
    ]
