# Generated by Django 3.1 on 2020-08-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200826_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='pic_folder/default.png', upload_to='photo_path'),
        ),
    ]
