# Generated by Django 3.1 on 2020-08-26 22:27

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200827_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='pic_folder/default.png', upload_to=api.models.photo_path),
        ),
    ]
